[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/api/subscribe"
  status = 200

[[redirects]]
  from = "/register"
  to = "/.netlify/functions/api/register"
  status = 200
